"""empty message

Revision ID: 239230b607da
Revises: 75f0ef00cd6d
Create Date: 2024-11-27 10:31:58.997073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239230b607da'
down_revision = '75f0ef00cd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('sensor_building_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'buildings', ['building_id'], ['building_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sensor_building_id_fkey', 'buildings', ['building_id'], ['id'])
        batch_op.alter_column('building_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
